name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_test_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Submodules
      run: |
        git submodule init
        git submodule update
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Build with meson
    
      run: |
        pip install --upgrade pip
        echo "PATH is $PATH"
        pip install .

    - name: Run tests
      run: | 
        pip install .[test]
        pytest tests

    - name: Install docs requirements
      run: |
        pip install .[docs]
        sudo apt install doxygen graphviz
    - name: Build the docs
      run: |
        cd docs
        mkdir doxyoutput
        doxygen
        make html
        cd ..
    # deployment taken from https://coderefinery.github.io/documentation/gh_workflow/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
        force_orphan: true