name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev
        pip install -r requirements.txt

    - name: Build with make
      run: make

    - name: Run tests
      run: | 
        export PYTHONPATH=$(pwd):$PYTHONPATH
        pytest tests
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Install docs requirements
      run: |
        pip install sphinx breathe
        sudo apt install doxygen graphviz
    - name: Build the docs
      run: |
        cd docs
        doxygen
        make html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
