name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_test_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev
        pip install -r requirements.txt

    - name: Build with make
      run: make

    - name: Run tests
      run: | 
        pip install -r requirements.txt
        pip install pytest
        export PYTHONPATH=$(pwd):$PYTHONPATH
        pytest tests

    - name: Install docs requirements
      run: |
        pip install -r requirements.txt
        pip install sphinx sphinx-rtd-theme breathe
        sudo apt install doxygen graphviz
    - name: Build the docs
      run: |
        cd docs
        mkdir doxyoutput
        doxygen
        make html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.DEPLOY_DOCS }}
        publish_dir: ./docs/_build/html
        publish_branch: gh-pages
