name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Submodules
      run: |
        git submodule init
        git submodule update
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev

    - name: Build with meson
    
      run: |
        pip install --upgrade pip
        echo "PATH is $PATH"
        pip install .[test]

    - name: Run tests
      run: | 
        pytest tests